### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by BBoldt** [superckl/RecipeTooltips#1]
https://gist.github.com/06763044bf228798d323

Not sure what caused it, just reporting it because I saw your mod mentioned.

**Comment by superckl** [comment]
Not really sure what would cause that... Please try with the latest release (1.0.17) and let me know if it happens again.

**Comment by Rapthera** [comment]
This issue occurs occasionally when I disconnect from a server.

Not always, occasionally.

**Comment by tterrag1098** [comment]
I know what is happening. When the client is disconnected from a server (or singleplayer) `Minecraft.thePlayer` is nulled out. Thus this line:

https://github.com/superckl/RecipeTooltips/blob/1d16b145eceeca126cb54fbcaa166e1e3daddb88/src/main/java/me/superckl/recipetooltips/handler/RenderTickHandler.java#L172

Will NPE.

**Comment by superckl** [comment]
Thanks @tterrag1098 

New version has been uploaded to CurseForge.
