### ISSUE TITLE
Conflict with JER worldgen plugin

### ISSUE THREAD

**Issue by thephoenixlodge** [superckl/RecipeTooltips#2]
Occurred when using the JET tooltip while looking at coal ore.
http://pastebin.com/FAWc7JH1

**Comment by superckl** [comment]
Issue is here:

https://github.com/mezz/JustEnoughItems/blob/1.8.9/src/main/java/mezz/jei/gui/TooltipRenderer.java#L36

No gui is open, please report to mezz. Not much I can do. Tell him I'm sorry for breaking everything with my fancy lack of guis.

https://github.com/mezz/JustEnoughItems/issues

**Comment by thephoenixlodge** [comment]
Been fixed on the JEI side now.
