### ISSUE TITLE
crash when alt tabing from game

### ISSUE THREAD

**Issue by Tsukiumy** [superckl/RecipeTooltips#3]
JustEnoughTooltips-1.10.2-2.1.35.jar
jei_1.10.2-3.12.2.291.jar
forge-1.10.2-12.18.1.2094.jar

here is the crashlog http://pastebin.com/UdNHNbfx
i was playing normally for a good time, then i just switched the window to change a music, and when i got back the game insta crashed.
Then i done the test 2 more times to see if it was just a java bug, just doing somenthing, tabbing, getting back, after 2 or 3 changes the game crashes.

**Comment by superckl** [comment]
JET is compiled with 3.10.0 of JEI. I only compile with release versions. Please either downgrade your JEI version or wait for a new release version and I'll update JET.

**Comment by superckl** [comment]
Since the only changes were actually improving the dependence on non-API classes, I released a beta version compiled with the latest JEI.

https://minecraft.curseforge.com/projects/justenoughtooltips/files/2333799

**Comment by mezz** [comment]
JEI 3.12.3 is now stable (non-beta).
