### ISSUE TITLE
Strange Crash (last version of (JEI and JET)(1.10.2)

### ISSUE THREAD

**Issue by Lightone** [superckl/RecipeTooltips#4]
when press the key of refill recipe when see any block  game freeze but dont end to crash.

Mod Versions:
jei_1.10.2-3.12.3.292
JustEnoughTooltips-1.10.2-2.1.36
forge-1.10.2-12.18.1.2073

and other 40 mods xD

this is the partial log.

[partial crash log](http://pastebin.com/reBvGAS0)

**Comment by superckl** [comment]
I'm going to need a full crash log to help you.
